MINIO_ENDPOINT=http://host.docker.internal:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin

MINIO_BRONZE_USERS_PATH=s3a://data-lake/bronze/users/
MINIO_SILVER_USERS_PATH=s3a://data-lake/silver/users/
MINIO_BRONZE_PRODUCTS_PATH=s3a://data-lake/bronze/products/
MINIO_SILVER_PRODUCTS_PATH=s3a://data-lake/silver/products/
MINIO_BRONZE_CARTS_PATH=s3a://data-lake/bronze/carts/
MINIO_SILVER_CARTS_PATH=s3a://data-lake/silver/carts/
MINIO_GOLD_PATH=s3a://data-lake/gold/customer_analytics/

MONGO_HOST=host.docker.internal
MONGO_DATABASE=customer_db
MONGO_COLLECTION=product

POSTGRES_HOST=host.docker.internal
POSTGRES_PORT=5432
POSTGRES_DATABASE=customer
POSTGRES_USER=postgres
POSTGRES_PASSWORD=admin1234
POSTGRES_RAW_TABLES=carts,cart_items
POSTGRES_DRIVER=org.postgresql.Driver

