from src.common.config_reader import load_properties
from pathlib import Path

ROOT_PATH = Path(__file__).resolve().parents[2]

CONFIG = load_properties(f"{ROOT_PATH}/config/dev.properties")

SPARK_MASTER = CONFIG["SPARK_MASTER"]

MINIO_ENDPOINT = CONFIG["MINIO_ENDPOINT"]
MINIO_ACCESS_KEY = CONFIG["MINIO_ACCESS_KEY"]
MINIO_SECRET_KEY = CONFIG["MINIO_SECRET_KEY"]

MINIO_BRONZE_USERS_PATH = CONFIG["MINIO_BRONZE_USERS_PATH"]
MINIO_BRONZE_PRODUCTS_PATH = CONFIG["MINIO_BRONZE_PRODUCTS_PATH"]
MINIO_SILVER_USERS_PATH = CONFIG["MINIO_SILVER_USERS_PATH"]
MINIO_SILVER_PRODUCTS_PATH = CONFIG["MINIO_SILVER_PRODUCTS_PATH"]
MINIO_BRONZE_CARTS_PATH = CONFIG["MINIO_BRONZE_CARTS_PATH"]
MINIO_SILVER_CARTS_PATH = CONFIG["MINIO_SILVER_CARTS_PATH"]
MINIO_GOLD_PATH = CONFIG["MINIO_GOLD_PATH"]

MONGO_HOST = CONFIG["MONGO_HOST"]
MONGO_DATABASE = CONFIG["MONGO_DATABASE"]
MONGO_COLLECTION = CONFIG["MONGO_COLLECTION"]
MONGO_READ_CONNECTION_URI = f"mongodb://{MONGO_HOST}/{MONGO_DATABASE}.{MONGO_COLLECTION}"

POSTGRES_HOST = CONFIG["POSTGRES_HOST"]
POSTGRES_PORT = CONFIG["POSTGRES_PORT"]
POSTGRES_DATABASE = CONFIG["POSTGRES_DATABASE"]
POSTGRES_USER = CONFIG["POSTGRES_USER"]
POSTGRES_PASSWORD = CONFIG["POSTGRES_PASSWORD"]
POSTGRES_RAW_TABLES = CONFIG["POSTGRES_RAW_TABLES"].split(",")
POSTGRES_DRIVER = CONFIG["POSTGRES_DRIVER"]
POSTGRES_URL = f"jdbc:postgresql://{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DATABASE}"
